// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.9
// source: os_res_data_basic.proto

package resdata

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "osgame/model/osserver/proto/osproto"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//####数据档头####
type DataBinHeader struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ContentHash string `protobuf:"bytes,1,opt,name=contentHash,proto3" json:"contentHash,omitempty"`
	RowCount    uint32 `protobuf:"varint,2,opt,name=rowCount,proto3" json:"rowCount,omitempty"`
	BodyLength  uint32 `protobuf:"varint,3,opt,name=bodyLength,proto3" json:"bodyLength,omitempty"`
}

func (x *DataBinHeader) Reset() {
	*x = DataBinHeader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_os_res_data_basic_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataBinHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataBinHeader) ProtoMessage() {}

func (x *DataBinHeader) ProtoReflect() protoreflect.Message {
	mi := &file_os_res_data_basic_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataBinHeader.ProtoReflect.Descriptor instead.
func (*DataBinHeader) Descriptor() ([]byte, []int) {
	return file_os_res_data_basic_proto_rawDescGZIP(), []int{0}
}

func (x *DataBinHeader) GetContentHash() string {
	if x != nil {
		return x.ContentHash
	}
	return ""
}

func (x *DataBinHeader) GetRowCount() uint32 {
	if x != nil {
		return x.RowCount
	}
	return 0
}

func (x *DataBinHeader) GetBodyLength() uint32 {
	if x != nil {
		return x.BodyLength
	}
	return 0
}

type DataBinBytes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hash     string           `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Records  [][]byte         `protobuf:"bytes,2,rep,name=records,proto3" json:"records,omitempty"`
	Registry *ResDataRegistry `protobuf:"bytes,3,opt,name=registry,proto3" json:"registry,omitempty"`
}

func (x *DataBinBytes) Reset() {
	*x = DataBinBytes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_os_res_data_basic_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataBinBytes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataBinBytes) ProtoMessage() {}

func (x *DataBinBytes) ProtoReflect() protoreflect.Message {
	mi := &file_os_res_data_basic_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataBinBytes.ProtoReflect.Descriptor instead.
func (*DataBinBytes) Descriptor() ([]byte, []int) {
	return file_os_res_data_basic_proto_rawDescGZIP(), []int{1}
}

func (x *DataBinBytes) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *DataBinBytes) GetRecords() [][]byte {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *DataBinBytes) GetRegistry() *ResDataRegistry {
	if x != nil {
		return x.Registry
	}
	return nil
}

type ResDataRegistry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Primaries []uint32                                 `protobuf:"varint,1,rep,packed,name=Primaries,proto3" json:"Primaries,omitempty"`
	Partials  map[uint32]*ResDataRegistry_MultiIndices `protobuf:"bytes,2,rep,name=Partials,proto3" json:"Partials,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *ResDataRegistry) Reset() {
	*x = ResDataRegistry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_os_res_data_basic_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResDataRegistry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResDataRegistry) ProtoMessage() {}

func (x *ResDataRegistry) ProtoReflect() protoreflect.Message {
	mi := &file_os_res_data_basic_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResDataRegistry.ProtoReflect.Descriptor instead.
func (*ResDataRegistry) Descriptor() ([]byte, []int) {
	return file_os_res_data_basic_proto_rawDescGZIP(), []int{2}
}

func (x *ResDataRegistry) GetPrimaries() []uint32 {
	if x != nil {
		return x.Primaries
	}
	return nil
}

func (x *ResDataRegistry) GetPartials() map[uint32]*ResDataRegistry_MultiIndices {
	if x != nil {
		return x.Partials
	}
	return nil
}

type I18N struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Records []*I18N_Record `protobuf:"bytes,1,rep,name=Records,proto3" json:"Records,omitempty"`
}

func (x *I18N) Reset() {
	*x = I18N{}
	if protoimpl.UnsafeEnabled {
		mi := &file_os_res_data_basic_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *I18N) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*I18N) ProtoMessage() {}

func (x *I18N) ProtoReflect() protoreflect.Message {
	mi := &file_os_res_data_basic_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use I18N.ProtoReflect.Descriptor instead.
func (*I18N) Descriptor() ([]byte, []int) {
	return file_os_res_data_basic_proto_rawDescGZIP(), []int{3}
}

func (x *I18N) GetRecords() []*I18N_Record {
	if x != nil {
		return x.Records
	}
	return nil
}

type ResDataRegistry_MultiIndices struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index []uint32 `protobuf:"varint,2,rep,packed,name=Index,proto3" json:"Index,omitempty"`
}

func (x *ResDataRegistry_MultiIndices) Reset() {
	*x = ResDataRegistry_MultiIndices{}
	if protoimpl.UnsafeEnabled {
		mi := &file_os_res_data_basic_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResDataRegistry_MultiIndices) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResDataRegistry_MultiIndices) ProtoMessage() {}

func (x *ResDataRegistry_MultiIndices) ProtoReflect() protoreflect.Message {
	mi := &file_os_res_data_basic_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResDataRegistry_MultiIndices.ProtoReflect.Descriptor instead.
func (*ResDataRegistry_MultiIndices) Descriptor() ([]byte, []int) {
	return file_os_res_data_basic_proto_rawDescGZIP(), []int{2, 0}
}

func (x *ResDataRegistry_MultiIndices) GetIndex() []uint32 {
	if x != nil {
		return x.Index
	}
	return nil
}

type I18N_Record struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key         string `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Translation string `protobuf:"bytes,2,opt,name=Translation,proto3" json:"Translation,omitempty"`
}

func (x *I18N_Record) Reset() {
	*x = I18N_Record{}
	if protoimpl.UnsafeEnabled {
		mi := &file_os_res_data_basic_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *I18N_Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*I18N_Record) ProtoMessage() {}

func (x *I18N_Record) ProtoReflect() protoreflect.Message {
	mi := &file_os_res_data_basic_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use I18N_Record.ProtoReflect.Descriptor instead.
func (*I18N_Record) Descriptor() ([]byte, []int) {
	return file_os_res_data_basic_proto_rawDescGZIP(), []int{3, 0}
}

func (x *I18N_Record) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *I18N_Record) GetTranslation() string {
	if x != nil {
		return x.Translation
	}
	return ""
}

var File_os_res_data_basic_proto protoreflect.FileDescriptor

var file_os_res_data_basic_proto_rawDesc = []byte{
	0x0a, 0x17, 0x6f, 0x73, 0x5f, 0x72, 0x65, 0x73, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x62, 0x61,
	0x73, 0x69, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x52, 0x65, 0x73, 0x44, 0x61,
	0x74, 0x61, 0x1a, 0x14, 0x72, 0x65, 0x73, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x6f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x13, 0x63, 0x6c, 0x74, 0x67, 0x65, 0x6e,
	0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x73, 0x0a,
	0x0d, 0x44, 0x61, 0x74, 0x61, 0x42, 0x69, 0x6e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x20,
	0x0a, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x48, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x48, 0x61, 0x73, 0x68,
	0x12, 0x1a, 0x0a, 0x08, 0x72, 0x6f, 0x77, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x08, 0x72, 0x6f, 0x77, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1e, 0x0a, 0x0a,
	0x62, 0x6f, 0x64, 0x79, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x0a, 0x62, 0x6f, 0x64, 0x79, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x3a, 0x04, 0xe0, 0x97,
	0x22, 0x01, 0x22, 0x78, 0x0a, 0x0c, 0x44, 0x61, 0x74, 0x61, 0x42, 0x69, 0x6e, 0x42, 0x79, 0x74,
	0x65, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x07, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73,
	0x12, 0x34, 0x0a, 0x08, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x18, 0x2e, 0x52, 0x65, 0x73, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x52, 0x65, 0x73,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x52, 0x08, 0x72, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x3a, 0x04, 0xe0, 0x97, 0x22, 0x01, 0x22, 0x83, 0x02, 0x0a,
	0x0f, 0x52, 0x65, 0x73, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79,
	0x12, 0x1c, 0x0a, 0x09, 0x50, 0x72, 0x69, 0x6d, 0x61, 0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0d, 0x52, 0x09, 0x50, 0x72, 0x69, 0x6d, 0x61, 0x72, 0x69, 0x65, 0x73, 0x12, 0x42,
	0x0a, 0x08, 0x50, 0x61, 0x72, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x26, 0x2e, 0x52, 0x65, 0x73, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x52, 0x65, 0x73, 0x44, 0x61,
	0x74, 0x61, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x2e, 0x50, 0x61, 0x72, 0x74, 0x69,
	0x61, 0x6c, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x08, 0x50, 0x61, 0x72, 0x74, 0x69, 0x61,
	0x6c, 0x73, 0x1a, 0x24, 0x0a, 0x0c, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x49, 0x6e, 0x64, 0x69, 0x63,
	0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0d, 0x52, 0x05, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x1a, 0x62, 0x0a, 0x0d, 0x50, 0x61, 0x72, 0x74,
	0x69, 0x61, 0x6c, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x3b, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x52, 0x65, 0x73,
	0x44, 0x61, 0x74, 0x61, 0x2e, 0x52, 0x65, 0x73, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x72, 0x79, 0x2e, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x49, 0x6e, 0x64, 0x69, 0x63, 0x65,
	0x73, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x3a, 0x04, 0xe0, 0x97,
	0x22, 0x01, 0x22, 0x7e, 0x0a, 0x04, 0x49, 0x31, 0x38, 0x4e, 0x12, 0x2e, 0x0a, 0x07, 0x52, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x52, 0x65,
	0x73, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x49, 0x31, 0x38, 0x4e, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x52, 0x07, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x1a, 0x3c, 0x0a, 0x06, 0x52, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x4b, 0x65, 0x79, 0x12, 0x20, 0x0a, 0x0b, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6c,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x54, 0x72, 0x61,
	0x6e, 0x73, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x3a, 0x08, 0xe0, 0x97, 0x22, 0x01, 0xe8, 0x97,
	0x22, 0x01, 0x42, 0x18, 0x5a, 0x16, 0x6f, 0x73, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x65, 0x73, 0x64, 0x61, 0x74, 0x61, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_os_res_data_basic_proto_rawDescOnce sync.Once
	file_os_res_data_basic_proto_rawDescData = file_os_res_data_basic_proto_rawDesc
)

func file_os_res_data_basic_proto_rawDescGZIP() []byte {
	file_os_res_data_basic_proto_rawDescOnce.Do(func() {
		file_os_res_data_basic_proto_rawDescData = protoimpl.X.CompressGZIP(file_os_res_data_basic_proto_rawDescData)
	})
	return file_os_res_data_basic_proto_rawDescData
}

var file_os_res_data_basic_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_os_res_data_basic_proto_goTypes = []interface{}{
	(*DataBinHeader)(nil),                // 0: ResData.DataBinHeader
	(*DataBinBytes)(nil),                 // 1: ResData.DataBinBytes
	(*ResDataRegistry)(nil),              // 2: ResData.ResDataRegistry
	(*I18N)(nil),                         // 3: ResData.I18N
	(*ResDataRegistry_MultiIndices)(nil), // 4: ResData.ResDataRegistry.MultiIndices
	nil,                                  // 5: ResData.ResDataRegistry.PartialsEntry
	(*I18N_Record)(nil),                  // 6: ResData.I18N.Record
}
var file_os_res_data_basic_proto_depIdxs = []int32{
	2, // 0: ResData.DataBinBytes.registry:type_name -> ResData.ResDataRegistry
	5, // 1: ResData.ResDataRegistry.Partials:type_name -> ResData.ResDataRegistry.PartialsEntry
	6, // 2: ResData.I18N.Records:type_name -> ResData.I18N.Record
	4, // 3: ResData.ResDataRegistry.PartialsEntry.value:type_name -> ResData.ResDataRegistry.MultiIndices
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_os_res_data_basic_proto_init() }
func file_os_res_data_basic_proto_init() {
	if File_os_res_data_basic_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_os_res_data_basic_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataBinHeader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_os_res_data_basic_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataBinBytes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_os_res_data_basic_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResDataRegistry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_os_res_data_basic_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*I18N); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_os_res_data_basic_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResDataRegistry_MultiIndices); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_os_res_data_basic_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*I18N_Record); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_os_res_data_basic_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_os_res_data_basic_proto_goTypes,
		DependencyIndexes: file_os_res_data_basic_proto_depIdxs,
		MessageInfos:      file_os_res_data_basic_proto_msgTypes,
	}.Build()
	File_os_res_data_basic_proto = out.File
	file_os_res_data_basic_proto_rawDesc = nil
	file_os_res_data_basic_proto_goTypes = nil
	file_os_res_data_basic_proto_depIdxs = nil
}
